version: '3'

services:
  db:
    image: postgres:alpine
    container_name: postgres_discover_cep
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      TZ: "America/Sao_Paulo"
    volumes:
      - ./pgsqldata:/var/lib/postgresql/data
    networks: 
      - network-api
  api:
    container_name: discover_cep_api
    image: discorver_cep_api
    depends_on:
      - db
    command: /bin/sh -c "yarn knex:migrate:undo && yarn knex:migrate && yarn knex:seed && yarn start"
    build: ./
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - '3333:3333'
    networks:
      - network-api
networks:
  network-api:
    external:
      name: network-api
